### ISSUE TITLE
Using after_transaction to fire off background jobs

### ISSUE THREAD

**Issue by openface** [grosser/ar_after_transaction#13]
I'm thinking about trying this gem to satisfy a requirement I have where I need to collect certain things about the model's changes, and hand them to a background job - but the background job must only be fired if the transaction is not rolled back.

For example:
```
class MyModel
  def before_save 
    after_transaction do
      SomeJob.async.new(some_information_only_available_from_the_before_save)
    end
  end
end
```

It's my understanding that this job then would not be fired until the model's save transaction is complete without being rolled back.    When the job runs, it will be handed whatever information was available at the time the `before_save` was invoked.

Is this a reasonable use case for using ar_after_transaction?   I'm just now discovering this gem, so I thought I'd be lazy and just ask directly before learning how it works.

Thanks.

**Comment by grosser** [comment]
no, the block would be executed when transation is complete, what would work:

```Ruby
before_save do
  @foo = some_information_only_available_from_the_before_save
end
after_commit do
  SomeJob.async.new @foo
end
```
