### ISSUE TITLE
Resolve rails dependency to 6.1.0

### ISSUE THREAD

**Issue by vladimirtemnikov** [grosser/ar_after_transaction#26]
Thank you for the awesome gem!

Currently this gem has a restriction to `< 6.1`, could it be updated to allow using the latest Rails version?

**Comment by grosser** [comment]
tried it, but does not work on 6.1 ... see https://github.com/grosser/ar_after_transaction/pull/28 for a starter
I don't have time for fixing this / I don't use the gem anymore, so please try fixing it :)

**Comment by grosser** [comment]
0.7.0
